version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
